"""adicionando o relacionamento fk

Revision ID: 29e398fa0452
Revises: d231f20b0994
Create Date: 2024-09-03 17:47:07.162224

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29e398fa0452'
down_revision: Union[str, None] = 'd231f20b0994'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'publicacao',
        'adm_direta_id',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema='processing',
    )
    op.alter_column(
        'publicacao',
        'divisao_adm_direta_id',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema='processing',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'publicacao',
        'divisao_adm_direta_id',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema='processing',
    )
    op.alter_column(
        'publicacao',
        'adm_direta_id',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema='processing',
    )
    # ### end Alembic commands ###
