"""adicionando ato

Revision ID: 36e27a825a91
Revises: 29e398fa0452
Create Date: 2024-09-04 10:23:44.592415

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36e27a825a91'
down_revision: Union[str, None] = '29e398fa0452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'ato',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('nome', sa.String(), nullable=True),
        sa.Column('sigla', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_ato_id')),
        sa.UniqueConstraint('nome', name=op.f('uq_ato_nome')),
        schema='dominio',
    )
    op.create_index(op.f('ix_ato_id'), 'ato', ['id'], unique=False, schema='dominio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ato_id'), table_name='ato', schema='dominio')
    op.drop_table('ato', schema='dominio')
    # ### end Alembic commands ###
