"""corringido o null constring para adm_indireta_id de publicacao

Revision ID: 77aaf12ec108
Revises: 2dee912336a4
Create Date: 2024-09-05 11:55:17.667107

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77aaf12ec108'
down_revision: Union[str, None] = '2dee912336a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'publicacao',
        'adm_indireta_id',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema='processing',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'publicacao',
        'adm_indireta_id',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema='processing',
    )
    # ### end Alembic commands ###
