"""adicionando o relacionamento fk

Revision ID: 780554f85ca0
Revises: 9906dee492bf
Create Date: 2024-09-03 16:31:50.052235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '780554f85ca0'
down_revision: Union[str, None] = '9906dee492bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publicacao', sa.Column('doe_bruto_id', sa.Integer(), nullable=False), schema='processing')
    op.drop_constraint('fk_publicacao_doe_nro_edicao_doe_bruto', 'publicacao', schema='processing', type_='foreignkey')
    op.create_foreign_key(op.f('fk_publicacao_doe_bruto_id_doe_bruto'), 'publicacao', 'doe_bruto', ['doe_bruto_id'], ['id'], source_schema='processing', referent_schema='processing')
    op.drop_column('publicacao', 'doe_nro_edicao', schema='processing')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publicacao', sa.Column('doe_nro_edicao', sa.INTEGER(), autoincrement=False, nullable=False), schema='processing')
    op.drop_constraint(op.f('fk_publicacao_doe_bruto_id_doe_bruto'), 'publicacao', schema='processing', type_='foreignkey')
    op.create_foreign_key('fk_publicacao_doe_nro_edicao_doe_bruto', 'publicacao', 'doe_bruto', ['doe_nro_edicao'], ['nro_edicao'], source_schema='processing', referent_schema='processing')
    op.drop_column('publicacao', 'doe_bruto_id', schema='processing')
    # ### end Alembic commands ###
