"""adicionando o relacionamento fk

Revision ID: 88c22fa5144d
Revises: c5e08b5e6b13
Create Date: 2024-09-03 17:23:33.149245

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88c22fa5144d'
down_revision: Union[str, None] = 'c5e08b5e6b13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
