"""permitindo null em alguns dominios

Revision ID: 9906dee492bf
Revises: 5ab03f2688c0
Create Date: 2024-09-03 04:38:43.613856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9906dee492bf'
down_revision: Union[str, None] = '5ab03f2688c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('adm_direta', 'sigla',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='dominio')
    op.alter_column('adm_indireta', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='dominio')
    op.alter_column('adm_indireta', 'sigla',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='dominio')
    op.alter_column('divisao_adm_direta', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='dominio')
    op.alter_column('divisao_adm_direta', 'sigla',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='dominio')
    # ### end Alembic commands ###

     # Inserir dados na tabela 'adm_indireta'
    op.execute(
        sa.text("""
            INSERT INTO dominio.adm_indireta (nome, sigla) VALUES
            ('NULL', 'NULL')
            ON CONFLICT (nome) DO NOTHING
        """)
    )

    # Inserir dados na tabela 'orgao_adm_indireta'
    op.execute(
        sa.text("""
            INSERT INTO dominio.divisao_adm_direta (nome, sigla) VALUES
            ('NULL', 'NULL')
            ON CONFLICT (nome) DO NOTHING
        """)
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('divisao_adm_direta', 'sigla',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='dominio')
    op.alter_column('divisao_adm_direta', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='dominio')
    op.alter_column('adm_indireta', 'sigla',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='dominio')
    op.alter_column('adm_indireta', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='dominio')
    op.alter_column('adm_direta', 'sigla',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='dominio')
    # ### end Alembic commands ###

    op.execute(
        sa.text("""
            DELETE FROM dominio.adm_indireta
            WHERE nome = 'NULL'
        """)
    )

    op.execute(
        sa.text("""
            DELETE FROM dominio.divisao_adm_indireta
            WHERE nome = 'NULL'
        """)
    )
