"""adicionando o relacionamento fk

Revision ID: c5e08b5e6b13
Revises: 2a795975a0b7
Create Date: 2024-09-03 17:21:58.015872

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5e08b5e6b13'
down_revision: Union[str, None] = '2a795975a0b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
