"""add col auditoria em publicacao

Revision ID: 3dabb7927524
Revises: 53eb17a416bb
Create Date: 2025-05-20 16:04:08.395886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dabb7927524'
down_revision: Union[str, None] = '53eb17a416bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publicacao', 
                  sa.Column('auditoria', sa.Boolean(), nullable=True, 
                            comment='Indicação se ocorreu a verificação do correto processamento do conteúdo da publicacao para ato.'), 
                            schema='processing')
    op.execute(sa.text('''
    -- View da tabela de publicacao
    CREATE OR REPLACE VIEW vw_publicacao AS
    SELECT 
        p.id, db.nro_edicao, db.dt_edicao, p2.nome AS poder,
        ad.nome AS adm_direta,
        dad.nome AS divisao_adm_direta,
        ai.nome AS adm_indireta,
        dai.nome AS divisao_adm_indireta,
        tp.nome AS tipo_publicacao, 
        p.nome_ato, p.identificador_link, p.link, p.conteudo_link, p.auditoria
    FROM processing.doe_bruto db 
    JOIN processing.publicacao p ON p.doe_bruto_id = db.id 
    LEFT JOIN dominio.poder p2 ON p.poder_id = p2.id 
    LEFT JOIN dominio.adm_direta ad ON p.adm_direta_id = ad.id
    LEFT JOIN dominio.adm_indireta ai ON p.adm_indireta_id = ai.id
    LEFT JOIN dominio.divisao_adm_direta dad ON p.divisao_adm_direta_id = dad.id
    LEFT JOIN dominio.divisao_adm_indireta dai ON p.divisao_adm_indireta_id = dai.id
    LEFT JOIN dominio.tipo_publicacao tp ON p.tipo_publicacao_id = tp.id;
    '''))
    # ### end Alembic commands ###
    
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publicacao', 'auditoria', schema='processing')
    # ### end Alembic commands ###
