"""ajustando as caracteristicas das colunas

Revision ID: 5500522d8e72
Revises: 7aa9a8934b04
Create Date: 2024-07-24 19:17:11.740979

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5500522d8e72'
down_revision: Union[str, None] = '7aa9a8934b04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'diario_oficial_bruto',
        'edicao',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema='processing',
    )
    op.alter_column(
        'diario_oficial_bruto',
        'exist',
        existing_type=sa.BOOLEAN(),
        nullable=False,
        schema='processing',
    )
    op.create_unique_constraint(None, 'diario_oficial_bruto', ['edicao'], schema='processing')
    op.create_unique_constraint(None, 'diario_oficial_bruto', ['data'], schema='processing')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'diario_oficial_bruto', schema='processing', type_='unique')
    op.drop_constraint(None, 'diario_oficial_bruto', schema='processing', type_='unique')
    op.alter_column(
        'diario_oficial_bruto',
        'exist',
        existing_type=sa.BOOLEAN(),
        nullable=True,
        schema='processing',
    )
    op.alter_column(
        'diario_oficial_bruto',
        'edicao',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema='processing',
    )
    # ### end Alembic commands ###
