"""comentario sobre a versão

Revision ID: 5794cd8b905a
Revises: 95a39bdef9ce
Create Date: 2024-07-23 16:18:16.766936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5794cd8b905a'
down_revision: Union[str, None] = '95a39bdef9ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
