"""testando chave estrangeira...

Revision ID: 6bdd57e019e5
Revises: b98a03b3b8b0
Create Date: 2024-08-07 16:14:54.056271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bdd57e019e5'
down_revision: Union[str, None] = 'b98a03b3b8b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ato_bruto', sa.Column('edicao_id', sa.Integer(), nullable=False), schema='processing')
    op.create_foreign_key(None, 'ato_bruto', 'diario_oficial_bruto', ['edicao_id'], ['edicao'], source_schema='processing', referent_schema='processing')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ato_bruto', schema='processing', type_='foreignkey')
    op.drop_column('ato_bruto', 'edicao_id', schema='processing')
    # ### end Alembic commands ###
