"""adicionando url a doe_bruto

Revision ID: 6fc8e4f473c6
Revises: e5c2ecd42738
Create Date: 2024-12-13 10:12:33.559215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fc8e4f473c6'
down_revision: Union[str, None] = 'e5c2ecd42738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doe_bruto', sa.Column('url', sa.String(), nullable=True, comment='Url de acesso ao diário oficial bruto.'), schema='processing')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doe_bruto', 'url', schema='processing')
    # ### end Alembic commands ###
