"""adicionando coluna processar dow bruto para publicacao

Revision ID: 7f5b8382be78
Revises: ef212d42ad21
Create Date: 2024-10-10 11:43:32.978727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f5b8382be78'
down_revision: Union[str, None] = 'ef212d42ad21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doe_bruto', sa.Column('doe_bruto_para_publicacao', sa.Boolean(), nullable=True, comment='Indicação se ocorreu o processamento do doe bruto para publicacao.'), schema='processing')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doe_bruto', 'doe_bruto_para_publicacao', schema='processing')
    # ### end Alembic commands ###
