"""comentario sobre a versão

Revision ID: 95a39bdef9ce
Revises: 14532f35de43
Create Date: 2024-07-23 15:53:00.918870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95a39bdef9ce'
down_revision: Union[str, None] = '14532f35de43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diario_oficial_bruto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('diario_oficial_json', sa.JSON(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('edicao', sa.Integer(), nullable=True),
    sa.Column('exist', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='processing'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diario_oficial_bruto', schema='processing')
    # ### end Alembic commands ###
