"""adicionando adm_indireta ao dominio

Revision ID: 9e09149daa8d
Revises: acbfd08711f3
Create Date: 2024-11-27 16:01:31.879148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e09149daa8d'
down_revision: Union[str, None] = 'acbfd08711f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divisao_adm_indireta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('sigla', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_divisao_adm_indireta_id')),
    sa.UniqueConstraint('nome', name=op.f('uq_divisao_adm_indireta_nome')),
    schema='dominio'
    )
    op.create_index(op.f('ix_divisao_adm_indireta_id'), 'divisao_adm_indireta', ['id'], unique=False, schema='dominio')
    # ### end Alembic commands ###

    # Inserir dados na tabela 'orgao_adm_indireta'
    op.execute(
        sa.text("""
            INSERT INTO dominio.divisao_adm_indireta (nome, sigla) VALUES
            ('Diretoria Geral', 'DG'),
            ('Diretoria', 'D'),
            ('Diretoria Administrativa', 'DIRAF')
            ON CONFLICT (nome) DO NOTHING
        """)
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_divisao_adm_indireta_id'), table_name='divisao_adm_indireta', schema='dominio')
    op.drop_table('divisao_adm_indireta', schema='dominio')
    # ### end Alembic commands ###
