"""New revision

Revision ID: a5960fdd549a
Revises: 5794cd8b905a
Create Date: 2024-07-24 17:17:36.547346

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5960fdd549a'
down_revision: Union[str, None] = '5794cd8b905a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'diario_oficial_bruto',
        'diario_oficial_json',
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
        schema='processing',
    )
    op.alter_column(
        'diario_oficial_bruto', 'data', existing_type=sa.DATE(), nullable=True, schema='processing'
    )
    op.alter_column(
        'diario_oficial_bruto',
        'edicao',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema='processing',
    )
    op.alter_column(
        'diario_oficial_bruto',
        'exist',
        existing_type=sa.BOOLEAN(),
        nullable=True,
        schema='processing',
    )
    op.drop_constraint(
        'diario_oficial_bruto_edicao_key',
        'diario_oficial_bruto',
        schema='processing',
        type_='unique',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        'diario_oficial_bruto_edicao_key', 'diario_oficial_bruto', ['edicao'], schema='processing'
    )
    op.alter_column(
        'diario_oficial_bruto',
        'exist',
        existing_type=sa.BOOLEAN(),
        nullable=False,
        schema='processing',
    )
    op.alter_column(
        'diario_oficial_bruto',
        'edicao',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema='processing',
    )
    op.alter_column(
        'diario_oficial_bruto', 'data', existing_type=sa.DATE(), nullable=False, schema='processing'
    )
    op.alter_column(
        'diario_oficial_bruto',
        'diario_oficial_json',
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
        schema='processing',
    )
    # ### end Alembic commands ###
