"""adicionando coluna processar publicacao para ato

Revision ID: acbfd08711f3
Revises: 7f5b8382be78
Create Date: 2024-10-11 13:44:36.866081

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acbfd08711f3'
down_revision: Union[str, None] = '7f5b8382be78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'publicacao',
        sa.Column(
            'processada_para_ato',
            sa.Boolean(),
            nullable=True,
            comment='Indicação se ocorreu o processamento do conteúdo da publicacao para ato.',
        ),
        schema='processing',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publicacao', 'processada_para_ato', schema='processing')
    # ### end Alembic commands ###
