"""testando 1...

Revision ID: b98a03b3b8b0
Revises: 65829fb284d8
Create Date: 2024-08-07 16:04:08.822689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b98a03b3b8b0'
down_revision: Union[str, None] = '65829fb284d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poder',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome'),
    schema='dominio'
    )
    op.create_table('ato_bruto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_ato', sa.String(), nullable=False),
    sa.Column('identificador_link', sa.String(), nullable=False),
    sa.Column('html_link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='processing'
    )
    op.create_table('diario_oficial_bruto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('diario_oficial_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('edicao', sa.Integer(), nullable=True),
    sa.Column('exist', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data'),
    sa.UniqueConstraint('edicao'),
    schema='processing'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diario_oficial_bruto', schema='processing')
    op.drop_table('ato_bruto', schema='processing')
    op.drop_table('poder', schema='dominio')
    # ### end Alembic commands ###
