"""add index nas tabelas

Revision ID: d7f8545789ca
Revises: 0fb49529f73b
Create Date: 2024-08-07 16:55:05.757423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7f8545789ca'
down_revision: Union[str, None] = '0fb49529f73b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_dominio_poder_id'), 'poder', ['id'], unique=False, schema='dominio')
    op.create_index(op.f('ix_processing_ato_bruto_id'), 'ato_bruto', ['id'], unique=False, schema='processing')
    op.create_index(op.f('ix_processing_diario_oficial_bruto_id'), 'diario_oficial_bruto', ['id'], unique=False, schema='processing')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_diario_oficial_bruto_id'), table_name='diario_oficial_bruto', schema='processing')
    op.drop_index(op.f('ix_processing_ato_bruto_id'), table_name='ato_bruto', schema='processing')
    op.drop_index(op.f('ix_dominio_poder_id'), table_name='poder', schema='dominio')
    # ### end Alembic commands ###
