"""iniciando o banco

Revision ID: ddc2a8bb4ed7
Revises: 
Create Date: 2024-08-31 09:09:53.414745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ddc2a8bb4ed7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poder',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_poder_id')),
    sa.UniqueConstraint('nome', name=op.f('uq_poder_nome')),
    schema='dominio'
    )
    op.create_index(op.f('ix_poder_id'), 'poder', ['id'], unique=False, schema='dominio')
    op.create_table('diario_oficial_bruto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('diario_oficial_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('edicao', sa.Integer(), nullable=True),
    sa.Column('exist', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diario_oficial_bruto_id')),
    sa.UniqueConstraint('data', name=op.f('uq_diario_oficial_bruto_data')),
    sa.UniqueConstraint('edicao', name=op.f('uq_diario_oficial_bruto_edicao')),
    schema='processing'
    )
    op.create_index(op.f('ix_diario_oficial_bruto_id'), 'diario_oficial_bruto', ['id'], unique=False, schema='processing')
    op.create_table('ato_bruto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('edicao_id', sa.Integer(), nullable=False),
    sa.Column('poder_id', sa.Integer(), nullable=False),
    sa.Column('nome_ato', sa.String(), nullable=False),
    sa.Column('identificador_link', sa.String(), nullable=False),
    sa.Column('html_link', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['edicao_id'], ['processing.diario_oficial_bruto.edicao'], name=op.f('fk_ato_bruto_edicao_id_diario_oficial_bruto')),
    sa.ForeignKeyConstraint(['poder_id'], ['dominio.poder.id'], name=op.f('fk_ato_bruto_poder_id_poder')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ato_bruto_id')),
    schema='processing'
    )
    op.create_index(op.f('ix_ato_bruto_id'), 'ato_bruto', ['id'], unique=False, schema='processing')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ato_bruto_id'), table_name='ato_bruto', schema='processing')
    op.drop_table('ato_bruto', schema='processing')
    op.drop_index(op.f('ix_diario_oficial_bruto_id'), table_name='diario_oficial_bruto', schema='processing')
    op.drop_table('diario_oficial_bruto', schema='processing')
    op.drop_index(op.f('ix_poder_id'), table_name='poder', schema='dominio')
    op.drop_table('poder', schema='dominio')
    # ### end Alembic commands ###
