"""delete cascade doe_bruto para publicacao

Revision ID: ec81bc3343e8
Revises: 59887b3ae575
Create Date: 2024-12-05 16:39:21.708327

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'ec81bc3343e8'
down_revision: Union[str, None] = '59887b3ae575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_publicacao_doe_bruto_id_doe_bruto', 'publicacao', schema='processing', type_='foreignkey')
    op.create_foreign_key(op.f('fk_publicacao_doe_bruto_id_doe_bruto'), 'publicacao', 'doe_bruto', ['doe_bruto_id'], ['id'], source_schema='processing', referent_schema='processing', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_publicacao_doe_bruto_id_doe_bruto'), 'publicacao', schema='processing', type_='foreignkey')
    op.create_foreign_key('fk_publicacao_doe_bruto_id_doe_bruto', 'publicacao', 'doe_bruto', ['doe_bruto_id'], ['id'], source_schema='processing', referent_schema='processing')
    # ### end Alembic commands ###
