"""mudando o nome da tabela

Revision ID: f4b90d808273
Revises: ef8d543771cb
Create Date: 2024-09-02 14:28:29.060582

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4b90d808273'
down_revision: Union[str, None] = 'ef8d543771cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'divisao_adm_direta',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('nome', sa.String(), nullable=False),
        sa.Column('sigla', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_divisao_adm_direta_id')),
        sa.UniqueConstraint('nome', name=op.f('uq_divisao_adm_direta_nome')),
        schema='dominio',
    )
    op.create_index(
        op.f('ix_divisao_adm_direta_id'),
        'divisao_adm_direta',
        ['id'],
        unique=False,
        schema='dominio',
    )
    op.drop_index('ix_orgao_adm_indireta_id', table_name='orgao_adm_indireta', schema='dominio')
    op.execute('DROP TABLE dominio.orgao_adm_indireta CASCADE')
    op.create_foreign_key(
        op.f('fk_publicacao_divisao_adm_direta_id_divisao_adm_direta'),
        'publicacao',
        'divisao_adm_direta',
        ['divisao_adm_direta_id'],
        ['id'],
        source_schema='processing',
        referent_schema='dominio',
    )

    op.execute(
        sa.text("""
            DELETE FROM dominio.orgao_adm_indireta
            WHERE nome = 'Diretoria Geral'
        """)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('fk_publicacao_divisao_adm_direta_id_divisao_adm_direta'),
        'publicacao',
        schema='processing',
        type_='foreignkey',
    )
    op.create_foreign_key(
        'fk_publicacao_divisao_adm_direta_id_orgao_adm_indireta',
        'publicacao',
        'orgao_adm_indireta',
        ['divisao_adm_direta_id'],
        ['id'],
        source_schema='processing',
        referent_schema='dominio',
    )
    op.create_table(
        'orgao_adm_indireta',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('sigla', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name='pk_orgao_adm_indireta_id'),
        sa.UniqueConstraint('nome', name='uq_orgao_adm_indireta_nome'),
        schema='dominio',
    )
    op.create_index(
        'ix_orgao_adm_indireta_id', 'orgao_adm_indireta', ['id'], unique=False, schema='dominio'
    )
    op.drop_index(
        op.f('ix_divisao_adm_direta_id'), table_name='divisao_adm_direta', schema='dominio'
    )
    op.drop_table('divisao_adm_direta', schema='dominio')
    # ### end Alembic commands ###
