"""Adicionando dominios

Revision ID: 7f0fcc2b350b
Revises: 7bcf5aa06c38
Create Date: 2024-09-01 11:26:57.881292

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f0fcc2b350b'
down_revision: Union[str, None] = '7bcf5aa06c38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'adm_direta',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('nome', sa.String(), nullable=False),
        sa.Column('sigla', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_adm_direta_id')),
        sa.UniqueConstraint('nome', name=op.f('uq_adm_direta_nome')),
        schema='dominio',
    )
    op.create_index(op.f('ix_adm_direta_id'), 'adm_direta', ['id'], unique=False, schema='dominio')
    op.create_table(
        'adm_indireta',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('nome', sa.String(), nullable=False),
        sa.Column('sigla', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_adm_indireta_id')),
        sa.UniqueConstraint('nome', name=op.f('uq_adm_indireta_nome')),
        schema='dominio',
    )
    op.create_index(
        op.f('ix_adm_indireta_id'), 'adm_indireta', ['id'], unique=False, schema='dominio'
    )
    op.create_table(
        'orgao_adm_indireta',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('nome', sa.String(), nullable=False),
        sa.Column('sigla', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_orgao_adm_indireta_id')),
        sa.UniqueConstraint('nome', name=op.f('uq_orgao_adm_indireta_nome')),
        schema='dominio',
    )
    op.create_index(
        op.f('ix_orgao_adm_indireta_id'),
        'orgao_adm_indireta',
        ['id'],
        unique=False,
        schema='dominio',
    )
    op.add_column(
        'publicacao', sa.Column('adm_direta_id', sa.Integer(), nullable=False), schema='processing'
    )
    op.add_column(
        'publicacao',
        sa.Column('adm_indireta_id', sa.Integer(), nullable=False),
        schema='processing',
    )
    op.add_column(
        'publicacao',
        sa.Column('orgao_adm_indireta_id', sa.Integer(), nullable=False),
        schema='processing',
    )
    op.create_foreign_key(
        op.f('fk_publicacao_adm_indireta_id_adm_indireta'),
        'publicacao',
        'adm_indireta',
        ['adm_indireta_id'],
        ['id'],
        source_schema='processing',
        referent_schema='dominio',
    )
    op.create_foreign_key(
        op.f('fk_publicacao_orgao_adm_indireta_id_orgao_adm_indireta'),
        'publicacao',
        'orgao_adm_indireta',
        ['orgao_adm_indireta_id'],
        ['id'],
        source_schema='processing',
        referent_schema='dominio',
    )
    op.create_foreign_key(
        op.f('fk_publicacao_adm_direta_id_adm_direta'),
        'publicacao',
        'adm_direta',
        ['adm_direta_id'],
        ['id'],
        source_schema='processing',
        referent_schema='dominio',
    )

    # Inserir dados na tabela 'adm_direta'
    op.execute(
        sa.text("""
            INSERT INTO dominio.adm_direta (nome, sigla) VALUES
            ('SECRETARIA DO MEIO AMBIENTE', 'SEMA')
            ON CONFLICT (nome) DO NOTHING
        """)
    )

    # Inserir dados na tabela 'adm_indireta'
    op.execute(
        sa.text("""
            INSERT INTO dominio.adm_indireta (nome, sigla) VALUES
            ('Instituto do Meio Ambiente e Recursos Hídricos - INEMA', 'INEMA')
            ON CONFLICT (nome) DO NOTHING
        """)
    )

    # Inserir dados na tabela 'orgao_adm_indireta'
    op.execute(
        sa.text("""
            INSERT INTO dominio.orgao_adm_indireta (nome, sigla) VALUES
            ('Diretoria Geral', 'DG')
            ON CONFLICT (nome) DO NOTHING
        """)
    )

    # Lista de valores a serem inseridos
    nomes = ['EXECUTIVO', 'LEGISLATIVO', 'JUDICIÁRIO']

    # Itera sobre cada valor e executa o INSERT
    for nome in nomes:
        op.execute(
            sa.text(f'INSERT INTO dominio.poder (nome) VALUES (\'{nome}\')'),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('fk_publicacao_adm_direta_id_adm_direta'),
        'publicacao',
        schema='processing',
        type_='foreignkey',
    )
    op.drop_constraint(
        op.f('fk_publicacao_orgao_adm_indireta_id_orgao_adm_indireta'),
        'publicacao',
        schema='processing',
        type_='foreignkey',
    )
    op.drop_constraint(
        op.f('fk_publicacao_adm_indireta_id_adm_indireta'),
        'publicacao',
        schema='processing',
        type_='foreignkey',
    )
    op.drop_column('publicacao', 'orgao_adm_indireta_id', schema='processing')
    op.drop_column('publicacao', 'adm_indireta_id', schema='processing')
    op.drop_column('publicacao', 'adm_direta_id', schema='processing')
    op.drop_index(
        op.f('ix_orgao_adm_indireta_id'), table_name='orgao_adm_indireta', schema='dominio'
    )
    op.drop_table('orgao_adm_indireta', schema='dominio')
    op.drop_index(op.f('ix_adm_indireta_id'), table_name='adm_indireta', schema='dominio')
    op.drop_table('adm_indireta', schema='dominio')
    op.drop_index(op.f('ix_adm_direta_id'), table_name='adm_direta', schema='dominio')
    op.drop_table('adm_direta', schema='dominio')

    # Remover os dados inseridos na reversão da migração
    op.execute(
        sa.text("""
            DELETE FROM dominio.adm_direta
            WHERE nome = 'SECRETARIA DO MEIO AMBIENTE'
        """)
    )

    op.execute(
        sa.text("""
            DELETE FROM dominio.adm_indireta
            WHERE nome = 'Instituto do Meio Ambiente e Recursos Hídricos - INEMA'
        """)
    )

    op.execute(
        sa.text("""
            DELETE FROM dominio.orgao_adm_indireta
            WHERE nome = 'Diretoria Geral'
        """)
    )

    op.execute(
        sa.text('DELETE FROM dominio.poder WHERE nome = :nome'),
        [{'nome': 'EXECUTIVO'}, {'nome': 'LEGISLATIVO'}, {'nome': 'JUDICIÁRIO'}],
    )
    # ### end Alembic commands ###
